services:
  mysql:
    image: mysql:8.0
    container_name: mydrive-mysql
    restart: always
    env_file:
      - ../.env.base
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: